name: identique_ratio-ci

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CONAN_USER_HOME: ~/.conan2

jobs:
  build_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cross toolchain & deps (ARM64 + Qt6)
        shell: bash
        run: |
            set -e
            sudo dpkg --add-architecture arm64
            CODENAME="$(. /etc/os-release && echo "$VERSION_CODENAME")"

            sudo bash -c "cat > /etc/apt/sources.list" <<EOF
            deb [arch=amd64] http://archive.ubuntu.com/ubuntu ${CODENAME} main restricted universe multiverse
            deb [arch=amd64] http://archive.ubuntu.com/ubuntu ${CODENAME}-updates main restricted universe multiverse
            deb [arch=amd64] http://security.ubuntu.com/ubuntu ${CODENAME}-security main restricted universe multiverse
            deb [arch=amd64] http://archive.ubuntu.com/ubuntu ${CODENAME}-backports main restricted universe multiverse
            EOF

            sudo find /etc/apt/sources.list.d -name "*.list" -exec sudo sed -i 's/^deb \(\[[^]]*\] \)\?/deb [arch=amd64] /' {} +

            sudo bash -c "cat > /etc/apt/sources.list.d/ubuntu-ports-arm64.list" <<EOF
            deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports ${CODENAME} main restricted universe multiverse
            deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports ${CODENAME}-updates main restricted universe multiverse
            deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports ${CODENAME}-security main restricted universe multiverse
            deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports ${CODENAME}-backports main restricted universe multiverse
            EOF

            sudo apt-get update

            sudo apt-get install -y \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            libc6-arm64-cross libc6-dev-arm64-cross \
            libgcc-s1-arm64-cross libstdc++6-arm64-cross \
            libv4l-dev:arm64 \
            qt6-base-dev:arm64 qt6-base-dev-tools \
            ninja-build cmake pkg-config fakeroot dpkg-dev

            python3 -m pip install --upgrade "conan~=2.2" ninja
            conan remote add --force conancenter https://center2.conan.io



      - uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.*','profiles/**') }}

      - name: Conan install (ARM64, HighGUI=Qt6, V4L2)
        env:
          # aide pkg-config pour librairies ARM64
          PKG_CONFIG_PATH: /usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
          PKG_CONFIG_LIBDIR: /usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
        run: |
          conan profile detect --force
          conan install . -of build/arm-qt \
            -pr:b profiles/default \
            -pr:h profiles/imx8mpevk \
            -s:h build_type=Release \
            -o opencv/*:highgui=True \
            -o opencv/*:with_qt=True \
            -o opencv/*:with_gtk=False \
            -o opencv/*:with_v4l=True \
            -o opencv/*:with_ffmpeg=False \
            -o opencv/*:with_gstreamer=False \
            -o opencv/*:with_jpeg=libjpeg-turbo \
            -o opencv/*:with_png=True \
            -c:h tools.system.package_manager:mode=install \
            -c:h tools.system.package_manager:sudo=True \
            --build=missing

      - name: CMake configure
        run: |
          cmake -S . -B build/arm -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=build/arm-qt/build/Release/generators/conan_toolchain.cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCPACK_DEBIAN_PACKAGE_ARCHITECTURE=arm64

      - name: Build
        run: cmake --build build/arm --parallel

      - name: Verify ELF
        run: file build/arm/identique_ratio

      - name: Generate Debian package (arm64)
        working-directory: build/arm
        env:
          CPACK_DEBIAN_PACKAGE_ARCHITECTURE: arm64
        run: cpack -G DEB -C Release

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: identique_ratio-deb-${{ github.sha }}
          path: build/arm/*.deb
