name: identique_ratio-ci

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CONAN_USER_HOME: ~/.conan2

jobs:
  build_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cross toolchain & deps (ARM64 + Qt6)
        shell: bash
        run: |
            set -e
            sudo dpkg --add-architecture arm64
            CODENAME="$(. /etc/os-release && echo "$VERSION_CODENAME")"

            sudo rm -f /etc/apt/sources.list
            sudo rm -f /etc/apt/sources.list.d/*.list
            sudo rm -f /etc/apt/sources.list.d/*.sources

            printf '%s\n' \
            'Types: deb' \
            "URIs: http://archive.ubuntu.com/ubuntu" \
            "Suites: ${CODENAME} ${CODENAME}-updates ${CODENAME}-backports" \
            'Components: main restricted universe multiverse' \
            'Architectures: amd64' \
            'Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg' \
            | sudo tee /etc/apt/sources.list.d/ubuntu-amd64.sources >/dev/null

            printf '%s\n' \
            'Types: deb' \
            "URIs: http://security.ubuntu.com/ubuntu" \
            "Suites: ${CODENAME}-security" \
            'Components: main restricted universe multiverse' \
            'Architectures: amd64' \
            'Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg' \
            | sudo tee /etc/apt/sources.list.d/ubuntu-amd64-security.sources >/dev/null

            printf '%s\n' \
            'Types: deb' \
            "URIs: http://ports.ubuntu.com/ubuntu-ports" \
            "Suites: ${CODENAME} ${CODENAME}-updates ${CODENAME}-backports ${CODENAME}-security" \
            'Components: main restricted universe multiverse' \
            'Architectures: arm64' \
            'Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg' \
            | sudo tee /etc/apt/sources.list.d/ubuntu-arm64.sources >/dev/null

            sudo apt-get clean
            sudo rm -rf /var/lib/apt/lists/*
            sudo apt-get update

            sudo apt-get install -y \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            libc6-arm64-cross libc6-dev-arm64-cross \
            libgcc-s1-arm64-cross libstdc++6-arm64-cross \
            libv4l-dev:arm64 \
            libgtk-3-dev:arm64 libglib2.0-dev:arm64 libgdk-pixbuf2.0-dev:arm64 \
            libpango1.0-dev:arm64 libcairo2-dev:arm64 \
            ninja-build cmake pkg-config fakeroot dpkg-dev

            python3 -m pip install --upgrade "conan~=2.2" ninja
            conan remote add --force conancenter https://center2.conan.io





      - uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.*','profiles/**') }}
      
      - name: Check pkg-config (gtk/v4l2) for ARM64
          env:
            PKG_CONFIG_PATH: /usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
            PKG_CONFIG_LIBDIR: /usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
          run: |
            pkg-config --print-errors --modversion gtk+-3.0
            pkg-config --print-errors --modversion v4l2


      - name: Conan install
        env:
          PKG_CONFIG_PATH: /usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
          PKG_CONFIG_LIBDIR: /usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
        run: |
          conan profile detect --force
          conan remove "wayland/*" -c || true
          conan remove "gtk/*" -c || true

          conan install . -of build/arm-headless \
            -pr:b profiles/default \
            -pr:h profiles/imx8mpevk \
            -s:h build_type=Release \
            -o opencv/*:highgui=True \
            -o opencv/*:with_gtk=True \
            -o opencv/*:with_qt=False \
            -o opencv/*:with_v4l=True \
            -o opencv/*:with_ffmpeg=False \
            -o opencv/*:with_gstreamer=False \
            -o opencv/*:with_jpeg=libjpeg-turbo \
            -o opencv/*:with_png=True \
            -o gtk/*:version=3 \
            -c:h tools.system.package_manager:mode=install \
            -c:h tools.system.package_manager:sudo=True \
            --build=missing

      - name: Cmake
        run: |
          cmake -S . -B build/arm -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=build/arm-headless/build/Release/generators/conan_toolchain.cmake \
            -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build/arm --parallel

      - name: Verify ELF
        run: file build/arm/identique_ratio



      - name: Generate Debian package
        working-directory: build/arm
        run: |
          cpack -G DEB -C Release
      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: identique_ratio-deb-${{ github.sha }}
          path: build/arm/*.deb



